### ISSUE TITLE
Fix bug for empty cart

### ISSUE THREAD

**Issue by travishaby** [TeamConchord/earmarked#39]
Fix the bug and build out tests to verify cart functionality

**Comment by mcschatz** [comment]
I'm having trouble figuring this out! Everywhere I put the flash notice, it does not populate. In the Cart Controller tried putting a flash notice in the show method, creating a before action, as well as putting it in both the candidate and issue methods. Any other ideas?

Also, there is a bug that has all everything - candidates, issues, and candidate_issues populating more than once.

**Comment by mcschatz** [comment]
I think there might be a sessions issue as a guest. My cart shows 6 different donations, but some of them are for the same candidate and issue. We do not have a "clear" method right now so our session never ends.

Thoughts on fixing this?

**Comment by travishaby** [comment]
Taking this one on, got a new bug coming up that wasn't happening before where the donations are getting overwritten....not sure why but I'm going to build out tests to make sure that doesn't happen
