### ISSUE TITLE
Issue donation redirects to candidate page

### ISSUE THREAD

**Issue by mcschatz** [TeamConchord/earmarked#40]

**Comment by mcschatz** [comment]
How do we want to handle this team?

**Comment by mcschatz** [comment]
created a new method within donations controller for the time being

**Comment by travishaby** [comment]
Interesting. We could have a candidate_donations controller and an issue_donations controller? Otherwise we could devise some sort of if else statement to redirect the two different routes

**Comment by travishaby** [comment]
Hah we're on the same page. I'm fine with that, everyone else on board? Go ahead and implement it and we can debate the merits when you submit the PR

**Comment by mcschatz** [comment]
my comment was deleted! yeah, i"ll push it up in a minute

**Comment by mcschatz** [comment]
i think having a redirect_method works for now
